### ISSUE TITLE
Multiple issues in the updated (tko-on-vsphere-with-tanzu) TKGS ref arch

### ISSUE THREAD

**Issue by laidbackware** [vmware-tanzu-labs/tanzu-validated-solutions#216] opened 2022-06-14 15:47 UTC
Commit [0430e71286845279ece644e880fcd2623158150d](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/commit/0430e71286845279ece644e880fcd2623158150d) introduced a large number of changes to the TKGS ref arch and a number of corrections are needed:

- This commit reverted the Registry section back to before [76dbf7178f39eeb4c800261a57a3779495bcf565](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/commit/76dbf7178f39eeb4c800261a57a3779495bcf565). The has a dangerously incorrect statement that Helm Harbor is support when it is not.
- Multus CNI is listed as supported, but all references point to the TKGM docs and not the TKGS docs. Multus is not supported with TKGS
- TKO-TKGS-003 states that namespaces logically separate workloads. This is not the case without NSX-T. The value in having a separate namespace is to separate authentication via vCenter roles.
- The NSX ALB Section says that [Layer 7 ingress is supported](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/reference-designs/tko-on-vsphere-with-tanzu.md#container-registry:~:text=L7%20ingress%20to%20the%20applications%20deployed%20in%20the%20Tanzu%20Kubernetes%20clusters), when in fact it is not supported/documented with TKGS. The TKGS install guide only cover layer 4 integration with Avi Essential.
- The network diagram should show the the TKG-Workload-PG01 network carries both data and control traffic, as all egress traffic from pods traverses this PG. The ref arch should also call out that it is not possible to use firewalls to isolate traffic between workload clusters, meaning the CNI must be used as the primary filtering mechanism. Antrea is the best CNI in this regard, as it has CRDs for FW rules that can be enforce before K8s network policy is added

**Comment by nithink-vmw** [comment] 2022-07-04 09:10
Triaged
Manish will be addressing it asap.

**Comment by laidbackware** [comment] 2022-07-04 09:38
I've already made the PR to revert the Harbor issue, as that needed fixing urgently
https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/226

**Comment by manishjha86** [comment] 2022-07-06 07:20
To address the above issues, I have raised https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/pull/230

**Comment by manishjha86** [comment] 2022-07-07 03:48
@laidbackware since your pull request has only changes related to the harbor, my pull request has changes related to the harbor, avi l7, and the firewall thing that you have highlighted. So I guess this pull request makes more sense. You can close your pull request as duplicate of #230

**Comment by laidbackware** [comment] 2022-07-07 10:12
@manishjha86 my PR reverts the Harbor statement of all 4 vSphere based ref archs to the statement that was previously agreed. You can either modify you PR to remove any changes to the Harbor section, or you can update your Harbor section to that it is the exact same as the section in my PR.

**Comment by manishjha86** [comment] 2022-07-08 04:20
I have modified the harbor section in my PR so wi think we are good to go

**Comment by nithink-vmw** [comment] 2022-07-11 09:05
Send email to IX to incorporate the changes

**Closed by nithink-vmw** 2022-07-11 09:05 UTC
Labels: bug

**Comment by laidbackware** [comment] 2022-07-11 10:17
@manishjha86 did you push the changes? The PR still shows you removing the Helm statement.
