### ISSUE TITLE
Prepare to Deploy Tanzu Kubernetes Clusters (Workload Cluster): Step 6: YAML fails

### ISSUE THREAD

**Issue by jeffjanderson** [vmware-tanzu-labs/tanzu-validated-solutions#215] opened 2022-06-13 13:34 UTC
**Describe the bug**
Applying the YAML in step 6 of [Deploy Tanzu Kubernetes Grid Supervisor Cluster](https://github.com/vmware-tanzu-labs/tanzu-validated-solutions/blob/main/src/deployment-guides/tko-on-vsphere-with-tanzu.md#--prepare-to-deploy-tanzu-kubernetes-clusters-workload-cluster) (sorry this link doesn't seem to snap to the right section) fails with:

```
error: error validating "tkgs.yaml": error validating data: ValidationError(TanzuKubernetesCluster.spec.topology.controlPlane.tkr): unknown field "name" in com.vmware.tanzu.run.v1alpha2.TanzuKubernetesCluster.spec.topology.controlPlane.tkr; if you choose to ignore these errors, turn validation off with --validate=false
```

**To Reproduce**
Please provide the steps to reproduce the behavior or a description of the content defect.
1. copy the YAML in step 6
2. observe the error above

**Expected behavior**
Was expecting the YAML to build a Tanzu Kubernetes Cluster

**Additional context**
Looks like the example just needs a couple more spaces before the name attribute under spec.topology.controlPlane.tkr.reference

**Comment by nithink-vmw** [comment] 2022-07-04 09:11
Triaged, 

Manish will fix the doc in RA1.5 by 07/15.

**Comment by manishjha86** [comment] 2022-07-07 03:55
I am reproducing this in my lab now

**Comment by manishjha86** [comment] 2022-07-07 05:59
I am able to reproduce the issue. I am getting the same error message that @jeffjanderson has highlighted. The correct yaml for the deployment should be as shown below
`apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: ra-test
  namespace: prod
spec:
  topology:
    controlPlane:
      replicas: 3
      vmClass: best-effort-medium
      storageClass: vsan-default-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: worker-pool01
      replicas: 3
      vmClass: best-effort-medium
      storageClass: vsan-default-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55`

I will get this fixed with the help of IX team

**Comment by manishjha86** [comment] 2022-07-08 04:19
An email has been sent to Meera and Dharmendra, providing them with the correct yaml file for replacing the existing yaml.

**Comment by manishjha86** [comment] 2022-07-12 04:02
As per discussion with the IX team, we decided to close this issue with no changes to documentation because the process is different in 1.5 and 1.4 is frozen and tagged. 

in TKO 1.5 documentation, the workload and shared services clusters are deployed directly through TMC and not through a yaml file.

**Closed by manishjha86** 2022-07-12 04:02 UTC
Labels: bug
