### ISSUE TITLE
Package install instructions causes errors during package deletion.

### ISSUE THREAD

**Issue by mtritabaugh** [vmware-tanzu-labs/tanzu-validated-solutions#102] opened 2022-03-04 00:04 UTC
**Describe the bug**
Installing packages into the same namespace where the application runs causes failure later when trying to delete it. Seems the service account get deleted too early and fails because it is still needed.

I think we should install all packages into a common namespace. ``` tanzu-user-managed``` or something similar.

Our contour section does change the namespace, per the official docs.  This should probably be reflected for all packages in the official docs.

https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/1.4/vmware-tanzu-kubernetes-grid-14/GUID-packages-ingress-contour.html
```The Contour and Envoy pods and any other resources associated with Contour and Envoy are created in the tanzu-system-ingress namespace; do not install the Contour package into this namespace.```

**To Reproduce**
Please provide the steps to reproduce the behavior or a description of the content defect.
1. Follow the instruction for installing cert-manager or harbor
2. Trying deleting the package

**Expected behavior**
Package should be deleted when running `tanzu package installed delete`

**Screenshots**
```
❮ tanzu package installed delete harbor -n tanzu-system-registry
Deleting installed package 'harbor' in namespace 'tanzu-system-registry'. Are you sure? [y/N]: y
| Uninstalling package 'harbor' from namespace 'tanzu-system-registry'
| Getting package install for 'harbor'
- Deleting package install 'harbor' from namespace 'tanzu-system-registry'


Error: package install deletion failed: Preparing kapp: Getting service account: serviceaccounts "harbor-tanzu-system-registry-sa" not found
```

```
❯ tanzu package installed delete cert-manager -n cert-manager
Deleting installed package 'cert-manager' in namespace 'cert-manager'. Are you sure? [y/N]: y
| Uninstalling package 'cert-manager' from namespace 'cert-manager'
\ Getting package install for 'cert-manager'
- Deleting package install 'cert-manager' from namespace 'cert-manager'
- Package uninstall status: Deleting


Error: package install deletion failed: Preparing kapp: Getting service account: serviceaccounts "cert-manager-cert-manager-sa" not found
```

**Additional context**

**Comment by manishjha86** [comment] 2022-06-11 13:46
In TKO 1.5 docs, package installation is done through the TMC catalog and we have tested it multiple times. This needs to be retested against tkgm 1.4 and if the issue is reproducible, the 1.4 docs need updating.

**Comment by nithink-vmw** [comment] 2022-07-04 09:23
Issue has been addressed in 1.5

**Closed by nithink-vmw** 2022-07-04 09:23 UTC
Labels: bug
